import { 
  FILES_CLI_COMMANDS, 
  HASH_CLI_COMMANDS, 
  NAVIGATION_CLI_COMMANDS, 
  OS_CLI_COMMANDS, 
  ZIP_CLI_COMMANDS 
} from "./commands.js";
import { 
  FILES_MANAGER,
  HASH_MANAGER, 
  NAVIGATION_MANAGER, 
  OS_MANAGER, 
  ZIP_MANAGER 
} from "./entities.js";

export const CLI_MAP = new Map([
  [NAVIGATION_CLI_COMMANDS, NAVIGATION_MANAGER],
  [FILES_CLI_COMMANDS, FILES_MANAGER],
  [OS_CLI_COMMANDS, OS_MANAGER],
  [HASH_CLI_COMMANDS, HASH_MANAGER],
  [ZIP_CLI_COMMANDS, ZIP_MANAGER]
]);